import { createApp } from 'vue'
import { createPinia } from 'pinia'
import piniaPluginPersistedstate from 'pinia-plugin-persistedstate'
import App from './App.vue'
import router from './router'
import i18n from './i18n'
import './assets/global.css'

// ── FontAwesome ──────────────────────────────────────────────────────────
import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

import { 
  // Solid Icons
  faChartBar,
  faBullhorn,
  faComments,
  faUser,
  faLock,
  faDoorOpen,
  faCreditCard,
  faRightFromBracket,
  faBars,
  faBuilding,
  faCheckCircle,
  faCheckDouble,
  faUserTie,
  faWrench,
  faHouse,
  faMoneyBill,
  faXmark,
  faMobileAlt,
  faTrash,
  faFloppyDisk,
  faBan,
  faStar,
  faTriangleExclamation,
  faKey,
  faSpinner,
  faEnvelope,
  faEye,
  faInfoCircle,
  faTv,
  faFutbol,
  faTrophy,
  faCalendarAlt,
  faSearch,
  faSync,
  faFilm,
  faPlus,
  faPlusCircle,
  faPen,
  faTimes,
  faCalendar,
  faFolderOpen,
  faLink,
  faTowerBroadcast,
  faSeedling,
  faSatellite,
  faGlobeAfrica,
  faCloudUploadAlt,
  faBrain,
  faBullseye,
  faCogs,
  faCode,
  faTag,
  faUsers,
  faBriefcase,
  faClock,
  faChartLine,
  faPlug,
  faCloud,
  faPalette,
  faArrowRight,
  faRocket,
  faCircleExclamation,
  faFolder,
  faFile,
  faEdit,
  faSave,
  faUndo,
  faRedo,
  faCopy,
  faPaste,
  faCut,
  faPrint,
  faDownload,
  faUpload,
  faShare,
  faHeart,
  faThumbsUp,
  faThumbsDown,
  faRotate,
  faReply,
  faPaperPlane,
  faSignInAlt,
  faUserPlus,
  faPhone,
  faLocationDot,
  faCog,
  faCoins,
  faRobot,
  faGamepad,
  faMusic,
  faCamera,
  faVideo,
  faHeadphones,
  faMicrophone,
  faDesktop,
  faLaptop,
  faTablet,
  faArrowRightToBracket,
  faArrowLeft,
  faSignOutAlt,
  faExclamationCircle,
  faBell,
  faUsersCog,
  faSlidersH,
  faShieldAlt,
  faExternalLinkAlt,
  faChevronRight,
  faChevronLeft,
  faThLarge,
  faCertificate,
  faExclamationTriangle,
  faCar,
  faMotorcycle,
  faTruckFront,
  faRoute,
  faShieldHalved,
  faHeadset,
  faCalendarCheck,
  faCarSide,
  faTruck,
  faFileContract,
  faMoneyBillWave,
  faIdCard,
  faFilePdf,
  faUserSlash,
  faUserCheck,
  faCloudArrowUp,
  faFileAlt,
  faFileImage,
  faFileWord,
  faClipboardList,
  faClipboard,
  faCircleXmark,
  faWandMagicSparkles,
  faBuildingColumns,
  faChevronUp,
  faChevronDown,
  faHandPointer,
  faMapLocationDot,
  faMobileScreenButton,
  faPlay,
  faRoad,
  faSatelliteDish,
  faTimesCircle,
  faUserFriends,
  faUserGear,
  faIdBadge,
  faUserPlus as faUserPlusSolid,
  faEyeSlash,
} from '@fortawesome/free-solid-svg-icons'

import { 
  faCalendar as faCalendarRegular,
  faEye as faEyeRegular,
  faStar as faStarRegular,
  faComment,
  faEnvelope as faEnvelopeRegular,
  faUser as faUserRegular,
  faPaperPlane as faPaperPlaneRegular,
  faClock as faClockRegular,
  faCircle as faCircleRegular,
  faCircleCheck as faCircleCheckRegular,
  faBell as faBellRegular,
} from '@fortawesome/free-regular-svg-icons'

import {
  faGithub,
  faTwitter,
  faLinkedin,
  faLinkedinIn,
  faFacebook,
  faFacebookF,
  faInstagram,
  faYoutube,
  faWhatsapp,
} from '@fortawesome/free-brands-svg-icons'

// Add all icons to library
library.add(
  faChartBar,
  faBullhorn,
  faComments,
  faUser,
  faLock,
  faDoorOpen,
  faCreditCard,
  faRightFromBracket,
  faBars,
  faBuilding,
  faCheckCircle,
  faCheckDouble,
  faUserTie,
  faWrench,
  faHouse,
  faMoneyBill,
  faXmark,
  faMobileAlt,
  faTrash,
  faFloppyDisk,
  faBan,
  faStar,
  faTriangleExclamation,
  faKey,
  faSpinner,
  faEnvelope,
  faEye,
  faInfoCircle,
  faTv,
  faFutbol,
  faTrophy,
  faCalendarAlt,
  faSearch,
  faSync,
  faFilm,
  faPlus,
  faPlusCircle,
  faPen,
  faTimes,
  faCalendar,
  faFolderOpen,
  faLink,
  faTowerBroadcast,
  faSeedling,
  faSatellite,
  faGlobeAfrica,
  faCloudUploadAlt,
  faBrain,
  faBullseye,
  faCogs,
  faCode,
  faTag,
  faUsers,
  faBriefcase,
  faClock,
  faChartLine,
  faPlug,
  faCloud,
  faPalette,
  faArrowRight,
  faRocket,
  faCircleExclamation,
  faFolder,
  faFile,
  faEdit,
  faSave,
  faUndo,
  faRedo,
  faCopy,
  faPaste,
  faCut,
  faPrint,
  faDownload,
  faUpload,
  faShare,
  faHeart,
  faThumbsUp,
  faThumbsDown,
  faRotate,
  faReply,
  faPaperPlane,
  faSignInAlt,
  faUserPlus,
  faPhone,
  faLocationDot,
  faCog,
  faCoins,
  faRobot,
  faGamepad,
  faMusic,
  faCamera,
  faVideo,
  faHeadphones,
  faMicrophone,
  faDesktop,
  faLaptop,
  faTablet,
  faArrowRightToBracket,
  faArrowLeft,
  faSignOutAlt,
  faExclamationCircle,
  faBell,
  faUsersCog,
  faSlidersH,
  faShieldAlt,
  faExternalLinkAlt,
  faChevronRight,
  faChevronLeft,
  faThLarge,
  faCertificate,
  faExclamationTriangle,
  faCar,
  faMotorcycle,
  faTruckFront,
  faRoute,
  faShieldHalved,
  faHeadset,
  faCalendarCheck,
  faCarSide,
  faTruck,
  faFileContract,
  faMoneyBillWave,
  faIdCard,
  faUserPlusSolid,
  faCalendarRegular,
  faEyeRegular,
  faStarRegular,
  faComment,
  faEnvelopeRegular,
  faUserRegular,
  faPaperPlaneRegular,
  faClockRegular,
  faCircleRegular,
  faCircleCheckRegular,
  faBellRegular,
  faFilePdf,
  faUserSlash,
  faUserCheck,
  faCloudArrowUp,
  faFileAlt,
  faFileImage,
  faFileWord,
  faClipboardList,
  faClipboard,
  faCircleXmark,
  faWandMagicSparkles,
  faBuildingColumns,
  faChevronUp,
  faChevronDown,
  faHandPointer,
  faMapLocationDot,
  faMobileScreenButton,
  faPlay,
  faRoad,
  faSatelliteDish,
  faTimesCircle,
  faUserFriends,
  faUserGear,
  faIdBadge,
  faEyeSlash,
  faGithub,
  faTwitter,
  faLinkedin,
  faLinkedinIn,
  faFacebook,
  faFacebookF,
  faInstagram,
  faYoutube,
  faWhatsapp,
)

const pinia = createPinia()
pinia.use(piniaPluginPersistedstate)

const app = createApp(App)
app.component('font-awesome-icon', FontAwesomeIcon)
app.use(pinia)
app.use(router)
app.use(i18n)
app.mount('#app')